version: '3.10'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    restart: always
    command: ["sh", "-c", "npm run start"]

  nginx:
    depends_on:
      - server
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d